### ISSUE TITLE
IndexOutOfBoundsException with parseIterator

### ISSUE THREAD

**Issue by scand1sk** [lihaoyi/fastparse#135]
I have a fairly complicated parser for the FlatZinc language available here: https://github.com/concrete-cp/cspom/blob/master/src/main/scala/cspom/flatzinc/FlatZincFastParser.scala

It seems to work pretty well when I convert the input stream to a whole String and parse it using the parse() method. However, I may have to parse quite large files (~ 500 MB) and would like to use the parseIterator() technique. I splitted the input stream into 1024 chars chunks with `val input = Source.fromInputStream(is).grouped(1024).map(_.mkString)`.

I got the following exception:
```
 java.lang.IndexOutOfBoundsException: UberBuffer index -1353 must be between 0 and 57
  at fastparse.utils.UberBuffer.apply(UberBuffer.scala:15)
  at fastparse.utils.IteratorParserInput.apply(ParserInput.scala:131)
  at fastparse.parsers.Terminals$.rec$1(Terminals.scala:93)
  at fastparse.parsers.Terminals$.startsWith(Terminals.scala:96)
  at fastparse.parsers.Terminals$Literal.parseRec(Terminals.scala:122)
  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:160)
  ...
```

Maybe I have done something wrong, but it may also be a bug in FastParse?

**Comment by vovapolu** [comment]
🤔  it looks like bug in fastparse. Can you send some basic working example with this error?

**Comment by vovapolu** [comment]
Oh, it's `WhitespaceApi` :) It's quite buggy with Iterator parsing.

**Comment by lihaoyi** [comment]
Bah `WhitespaceApi` is always a source of bugs and internal confusion 😛 if only it wasn't so useful!
