### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space when parsing

### ISSUE THREAD

**Issue by softinio** [lihaoyi/fastparse#142]
Have these parser: 

```
val digits = P(CharIn('0'to'9').rep.!)
val streetNumber = P(StringInIgnoreCase("and","thousand","hundred","zero","one","two","three","four","five","six","seven","eight","nine","ten","twenty","thirty","forty","fourty","fifty","sizty","seventy","eighty","ninety").rep.!)
val streetName = P( (digits | streetNumber).rep ~/ CharIn('a' to 'z', 'A' to 'Z', '0' to '9' ).rep.!
```

this is the unit test I am running: 

```
it should "Parse street name" in {
    val sample = "1919 Lynn Street"
    val Parsed.Success(value, _) = PostingParser.streetName.parse(sample)
    println(value)
    value should equal("Lynn Street")
  }
```

This is the java exception I get: 

```
[error] Uncaught exception when running com.snagajob.http.utils.PostingParserTest: java.lang.OutOfMemoryError: Java heap space
sbt.ForkMain$ForkError: Java heap space
	at scala.collection.mutable.ResizableArray.ensureSize(ResizableArray.scala:103)
	at scala.collection.mutable.ResizableArray.ensureSize$(ResizableArray.scala:93)
	at scala.collection.mutable.ArrayBuffer.ensureSize(ArrayBuffer.scala:48)
	at scala.collection.mutable.ArrayBuffer.$plus$eq(ArrayBuffer.scala:84)
	at scala.collection.mutable.ArrayBuffer.$plus$eq(ArrayBuffer.scala:48)
	at fastparse.core.Implicits$LowPriRepeater$GenericRepeater.accumulate(Implicits.scala:47)
	at fastparse.core.Implicits$LowPriRepeater$GenericRepeater.accumulate(Implicits.scala:44)
	at fastparse.parsers.Combinators$Repeat.rec$3(Combinators.scala:462)
	at fastparse.parsers.Combinators$Repeat.parseRec(Combinators.scala:489)
	at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
	at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:160)
	at fastparse.core.Parser.parseInput(Parsing.scala:376)
	at fastparse.core.Parser.parse(Parsing.scala:358)
	at com.snagajob.http.utils.PostingParserTest.$anonfun$new$4(PostingParserTest.scala:27)
	at com.snagajob.http.utils.PostingParserTest$$Lambda$82/256972736.apply(Unknown Source)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike.invokeWithFixture$1(FlatSpecLike.scala:1680)
	at org.scalatest.FlatSpecLike.$anonfun$runTest$1(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpecLike$$Lambda$125/826229456.apply(Unknown Source)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FlatSpecLike.runTest(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpecLike.runTest$(FlatSpecLike.scala:1674)
	at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike.$anonfun$runTests$1(FlatSpecLike.scala:1750)
```

Bug or am I doing something wrong as using `fastparse` for the first time? 

I do have my heap set to 2G so would have thought its enough.

Thanks.

**Comment by softinio** [comment]
Closing as issue was with me not writing my parsers efficiently.

Changed to this and it all worked: 

```
val streetName = P( CharsWhile(c => ('0' to '9' contains c) ) ~/ CharsWhile(c => ('a' to 'z' contains c) | ('A'to 'Z' contains c)|('0' to '9' contains c)| (" \r\n" contains c)).!)
```
