### ISSUE TITLE
NoSuchMethodError when trying to compile

### ISSUE THREAD

**Issue by rintcius** [lihaoyi/fastparse#161]
On current `master` I am running into:

```
java.lang.NoSuchMethodError: fastparse.all$.parserApi(Ljava/lang/Object;Lscala/Function1;)Lfastparse/ParserApi;
	at coursier.ivy.PropertiesPattern$Parser$.<init>(Pattern.scala:127)
	at coursier.ivy.PropertiesPattern$Parser$.<clinit>(Pattern.scala)
	at coursier.ivy.PropertiesPattern$.parser(Pattern.scala:142)
	at coursier.ivy.PropertiesPattern$.parse(Pattern.scala:146)
	at coursier.Tasks$.coursier$Tasks$$globalPluginPattern$lzycompute(Tasks.scala:300)
	at coursier.Tasks$.coursier$Tasks$$globalPluginPattern(Tasks.scala:281)
	at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:460)
	at coursier.Tasks$$anonfun$resolutionTask$1.apply(Tasks.scala:317)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
[error] (scalaparseJVM/*:coursierResolution) java.lang.NoSuchMethodError: fastparse.all$.parserApi(Ljava/lang/Object;Lscala/Function1;)Lfastparse/ParserApi;
```

See https://github.com/coursier/coursier/issues/468 for a similar report. I haven't tried #159, but upgrading Coursier solves this issue:
```
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC10")
```

Happy to put a separate PR up if #159 can't be merged for some reason.

**Comment by olafurpg** [comment]
Thank you for reporting @rintcius. #159 just got merged, are you able now to build the project on the master branch?

**Comment by rintcius** [comment]
Yes it works now, thanks @olafurpg
