### ISSUE TITLE
Spark Error Serializing fastparse.Parsed

### ISSUE THREAD

**Issue by ClintCombs** [lihaoyi/fastparse#202]
When running as part of a Spark job, serialization errors occur:

```18/11/19 16:30:11 ERROR TaskResultGetter: Exception while getting task result
java.io.InvalidClassException: fastparse.Parsed$Success; no valid constructor
    at java.io.ObjectStreamClass$ExceptionInfo.newInvalidClassException(ObjectStreamClass.java:150)
    at java.io.ObjectStreamClass.checkDeserialize(ObjectStreamClass.java:790)
    at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2001)
    at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
    ...
```

**Comment by ClintCombs** [comment]
This happened when trying to collect results from an RDD.

**Comment by ClintCombs** [comment]
I'll have to test to see if this is a result of `Parsed` being a `sealed trait`. If so, it may not make sense to change this. The workaround for now is to transform any `Parsed` instances into something else.

**Comment by ClintCombs** [comment]
I see no reason for this issue to be solved here. Users of the library should transform `Parsed._` results into application-specific case classes within their Spark job.
