### ISSUE TITLE
Infinite loop while constructing ParseError

### ISSUE THREAD

**Issue by jeroenr** [lihaoyi/fastparse#77]
I have this problem where I'm getting stuck in an infinite loop while constructing ParseError. So the actual parsing completes, results into an error and then when I try to construct ParseError it's getting stuck into a loop while building the error trace. I'm using Fastparse version 0.3.4.

It looks like it's getting stuck [here](https://github.com/lihaoyi/fastparse/blob/master/fastparse/shared/src/main/scala/fastparse/parsers/Combinators.scala#L439-L444). The stack looks like this while it's stuck:

```
	  at scala.collection.generic.Growable$class.loop$1(Growable.scala:54)
	  at scala.collection.generic.Growable$class.$plus$plus$eq(Growable.scala:57)
	  at scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:183)
	  at scala.collection.immutable.List.$colon$colon$colon(List.scala:128)
	  at fastparse.parsers.Combinators$Either.rec$4(Combinators.scala:444)
	  at fastparse.parsers.Combinators$Either.parseRec(Combinators.scala:447)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  - locked <0x961> (a fastparse.parsers.Combinators$Rule)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.parsers.Combinators$Either.rec$4(Combinators.scala:439)
	  at fastparse.parsers.Combinators$Either.parseRec(Combinators.scala:447)
	  at fastparse.parsers.Combinators$Capturing.parseRec(Combinators.scala:22)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  - locked <0x964> (a fastparse.parsers.Combinators$Rule)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.parsers.Combinators$Either.rec$4(Combinators.scala:439)
	  at fastparse.parsers.Combinators$Either.parseRec(Combinators.scala:447)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.parsers.Combinators$Repeat.rec$3(Combinators.scala:373)
	  at fastparse.parsers.Combinators$Repeat.parseRec(Combinators.scala:409)
	  at fastparse.parsers.Combinators$Capturing.parseRec(Combinators.scala:22)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:32)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.parsers.Combinators$Sequence$Flat.rec$1(Combinators.scala:247)
	  at fastparse.parsers.Combinators$Sequence$Flat.parseRec(Combinators.scala:268)
	  at fastparse.parsers.Combinators$Either.rec$4(Combinators.scala:439)
	  at fastparse.parsers.Combinators$Either.parseRec(Combinators.scala:447)
	  at fastparse.parsers.Combinators$Capturing.parseRec(Combinators.scala:22)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:32)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.parsers.Combinators$Either.rec$4(Combinators.scala:439)
	  at fastparse.parsers.Combinators$Either.parseRec(Combinators.scala:447)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.parsers.Combinators$Repeat.rec$3(Combinators.scala:373)
	  at fastparse.parsers.Combinators$Repeat.parseRec(Combinators.scala:409)
	  at fastparse.parsers.Combinators$Capturing.parseRec(Combinators.scala:22)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:32)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.parsers.Combinators$Either.rec$4(Combinators.scala:439)
	  at fastparse.parsers.Combinators$Either.parseRec(Combinators.scala:447)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.parsers.Combinators$Repeat.rec$3(Combinators.scala:373)
	  at fastparse.parsers.Combinators$Repeat.parseRec(Combinators.scala:409)
	  at fastparse.parsers.Combinators$Capturing.parseRec(Combinators.scala:22)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:32)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.parsers.Combinators$Sequence$Flat.rec$1(Combinators.scala:247)
	  at fastparse.parsers.Combinators$Sequence$Flat.parseRec(Combinators.scala:268)
	  at fastparse.parsers.Combinators$Either.rec$4(Combinators.scala:439)
	  at fastparse.parsers.Combinators$Either.parseRec(Combinators.scala:447)
	  at fastparse.parsers.Combinators$Capturing.parseRec(Combinators.scala:22)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:32)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.parsers.Combinators$Either.rec$4(Combinators.scala:439)
	  at fastparse.parsers.Combinators$Either.parseRec(Combinators.scala:447)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.parsers.Combinators$Repeat.rec$3(Combinators.scala:373)
	  at fastparse.parsers.Combinators$Repeat.parseRec(Combinators.scala:409)
	  at fastparse.parsers.Combinators$Capturing.parseRec(Combinators.scala:22)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:32)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.parsers.Combinators$Sequence$Flat.rec$1(Combinators.scala:247)
	  at fastparse.parsers.Combinators$Sequence$Flat.parseRec(Combinators.scala:268)
	  at fastparse.parsers.Combinators$Either.rec$4(Combinators.scala:439)
	  at fastparse.parsers.Combinators$Either.parseRec(Combinators.scala:447)
	  at fastparse.parsers.Combinators$Capturing.parseRec(Combinators.scala:22)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.fastparse$parsers$Combinators$Rule$$res$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:32)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
	  at fastparse.WhitespaceApi$CustomSequence.parseRec(WhitespaceApi.scala:26)
	  at fastparse.parsers.Combinators$Rule.res$lzycompute$1(Combinators.scala:142)
	  at fastparse.parsers.Combinators$Rule.parseRec(Combinators.scala:147)
	  at fastparse.core.Parsed$TracedFailure$.apply(Parsing.scala:199)
	  at fastparse.core.Parsed$Failure$Extra$Impl.traced$lzycompute(Parsing.scala:116)
	  - locked <0x982> (a fastparse.core.Parsed$Failure$Extra$Impl)
	  at fastparse.core.Parsed$Failure$Extra$Impl.traced(Parsing.scala:116)
	  at fastparse.core.ParseError.<init>(Parsing.scala:34)
```

To reproduce:

Clone [this](https://github.com/jeroenr/gnip-rule-validator/tree/07c0fd6b1bdd149e26c440c11652cd5f5e080f99) and run the tests

As discussed at 29-02-2016 in [gitter](https://gitter.im/lihaoyi/fastparse) the solution might be to provide a flag to ParseError which can be plumbed down into failure.extra.traced which disables the construction of traceParsers or to call .distinct on traceParsers at every step, to stop it from blowing up to infinity in these cases

**Comment by jeroenr** [comment]
I figured out that the problem occurs only if I use the WhitespaceApi. So it looks like the problem is somewhere [here](https://github.com/lihaoyi/fastparse/blob/master/fastparse/shared/src/main/scala/fastparse/WhitespaceApi.scala#L22-L48)

**Comment by lihaoyi** [comment]
Fixed by https://github.com/lihaoyi/fastparse/pull/79
